services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AK\TimelineVis\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  # Called by makeInstance from EXT:form
  AK\TimelineVis\Middleware\AjaxDispatcher:
    public: true